[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "3b2ca146b6065bd94fcd3ba728a58e596b21a9aa"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "ec99a68e75b089e4653c6c7e632fc12db13f95ff052c2793627bde95c40d3617"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a69f7e9e692879c1dba97f80f7964eefa51b504"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "738a08f773a13c9a162f60173b0437bf3d9445081da49d31a634f69933c5382d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84d2ca953d6d1b0569e59fc4b48e9229e843aee7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "6d468b1d71ab3fa4e488eb656b5903b2c93ffb19996b86068abab5d88a735112"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cdc6faecf1764012b568a118af4c71498e45c31"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "1c2463e51d843bbf2882c8dbfb52cec63ba010b67aea876e8a12b3a41de3a8f3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f903364ad516543334899456a7a962e47df22b1"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "4cfb8e202088a2176559bf7280ae9bba88ee54d1c6fe3e8539a6804a84db5f0c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ae053df1aa77fff0809398e920a6dfd45ebff9b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "0f82c8e6e7df9a8005d20603c4a33fba4a71f957a34ec95a23561574e24e17e4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64476fdf8338e3758a8deee915507897c9e9ae0b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "6358b8be289cd6bda3857c7b31bbfdb36ddbf48ef2e2fd938344216b04b22612"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "11e7e7e5b0d6272129149db0e9651fa4f29d21c0"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "6f0b502fa6dc4a1878a9559825435104cc2599a3b12d4ff765870e077e6e7c30"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77f53db9c2993bd1c8f9767a6b8405f18c91b410"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "188b8f0810cb7e5c531e84d09b38408ed57182004de99d486d17c0e61e1146e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6cf9b4288c9353579f593642cb28baa5194dfff"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "5d1bdc438bb508324cd2b6c94308de51795183e6774e8f544cf067f3e671938a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8dc9a28f27276c4f77fea55797865b4133bb379"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "f2b4dde9bee16b080935e37665e83465ea9f658a1b3904e9c32b04f345ca43f9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b09f808b5e0b8f9f98e5aeae0d13a578545c13"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "7bd2d47a6d13c89cd9906d87f4c85ea014a72184f109ff9921f1ac16e94f8c2a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "d2a86744ee625bcf17ea1189a3cfcaaeb0ff6460"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "825521441c7cb0e7671a4fd36416e84c8e79c746060561f1d02f8cf317ca5435"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+0/GAP_pkg_json.v200.100.0.x86_64-unknown-freebsd.tar.gz"
