[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "f12ac76f02d335010be6adddfdb9655ebbf61a6a"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "da9d5ce0f5cf7551fe12be91a142ba160ae70141c76991202a0d58e89d7d060c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b61b0b802ff9f91eca06f3b895e53b07d6bd227"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "e6bdcc011f926c29dd7ca00b93186ccba213ba63248c376568d450aa1279e374"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38131cb0e3e2a4013ab22f11efec9dc475d09efd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "afe30ee599f4f2679b596371f96f1c18520a3177490a7ec78881940600ca1a17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fbfbc37c27d7fc6d62460d856b7767982d7d20a"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "07e87e9083697d3092fe14f485bb5478b61c95c5d903d25ee09794e7f89d4137"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81070b1067d1253c464580e0139b473316b5e385"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "16e36cdd87526adefcd1f01d2f73f8f58b19ee91d2b921fb5e10c2b3ac5924a2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45547e5c196174e4270c24dad361684f94d6f7e1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "85628d86ee75138f19a9081a84d94ac05afb800967a303dea9f040ee7766c53e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aadd102c299cfbe01928d963b45613770dd0be13"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "089d1d34a721eb20ce9ff90b9570c7b576b062a081fe44a625a0049b5375c8eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "febfce091ed54d68222c4a6c55d7284a06f7797f"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "6c90be72552bbfbf561ff5e50133cc5da78336a3d0c7d013914185c743b77875"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "557d82ea8e5619ee0ab636dc947552d07277e7a6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "be1c7744cdd755d7436f42c0728c0daf556de3ea191c972f1d763830e2705322"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49accbe215ec219ba4ad6a3a7e1b931a6eb00306"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "138c23deec3d6358ffb913f450c63e427b98020e36b3228c0a61243a95df8672"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba1614ec67bc17a832145f088497034f686516f0"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "a13b7be79d4af8227242644c5f5deb93b5dd20ab5a7bc0559ec8548e4e964793"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "815d26d3b7aee8c5c7021b38cc5583f0294a3d4f"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "31dc1c95d81096cf7e5effcdcf1ca96d53879f3f8b399b16c177213ffa5ff9e4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "ce9a3f34ce393aa6d4beeaaefa2b939acd3199d4"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "7d38f406050d50f319db2bdf6099deced63d71d58cab6098f07dc11827a87ffc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+1/GAP_pkg_json.v200.200.200.x86_64-unknown-freebsd.tar.gz"
