[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "d778069d42bcc3d28dff21c33cddec6d66ab1f2a"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "8a842e37760620920663058172badfd9afd7c9f960257b2c1109d361ab0b6927"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca4f10530b3cd750705fcae6221ee50aaf84eac8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "c8fcd63b3178458b74f48221de2464c76a93b2ea1979b5c38139bd4f3cdb855f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddfba000755f10c1895d47e831f8601c37d2235c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "3c436c3c23495477abe7da256bf948a8bfa6e440142e3ee22661dc12a6eb3bb2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6351248d5b3c2adc85529b80add23dd37d25578a"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "fb136346cec37a48319bb1b88ea66ae1f41ebe8121feae1c20d14e03424ffce8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e7a2c71a8f41bd37d1f12e2e1645fffee363276"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "e6e99c80676895d181d0a9bc7257ebbb4c2af4e9a05615b6a280e8aba5fb1313"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc5eb981d4b096bfdc8dccd7bb9ff3b4f6de643f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "5f6311d96f609f5faa2ae6d6d91a1cd4d02722d6370ed08b71d08ebe0ca1dfa6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0602d5527c8c9a13d889aa5d2e4cddb0d90d057a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "fce26b723be906d3652763d6b1b56360a45ac4abfe3902ceca48548bf146c6ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "1da27e962a7e5fe0cb15a45762faf2e093a2611f"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "77fcedd82e0b7a446dcd47656e8a45ea5a1b0752a51b254080433bdf27806424"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "592b0f1e5f9ec913b43cbc7b120cc6a2038fe8ed"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "216d341413c5bbc5d25e747134a6a3dd64d9a133ecee37121d38b4174ff5c0b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13474a289f7b60c204d39e2af6a5f551045c686d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "e28eb0f964da427dc67d170163badcbf57da7ef07bba56a9fe57c024cbdb6cb4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5444fe771be7042e99d72e17278d52da7eca9d0"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "86c546d19b932c954791532d0a598bdabf953e3833a003f56bd48298c5045d41"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c30ab02496bb9330af56f750ca10a8cf97dcb916"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "42ed96de563285e389c7de2edad9a44bac8299007c441666021d44c60aaa6306"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "66ac53a639d2ce49787d7e364950dda359242205"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "1d20599cc519f8d24684f72b057bc65315e1e09917e0f5283362c5aff74b917d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.101+0/GAP_pkg_json.v200.100.101.x86_64-unknown-freebsd.tar.gz"
