[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "b8a1f1e038d05c7071402dc0567b4b92effe63bf"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "0bfa822e3f0ee6e2278681de05c6f1f6968bf8b23dbf54a2fcdee2a2402d029b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b9c5efde4c2fb1449069e3be5fa1f3ba736271e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "2afb40a491a3b996d017a3ee82d964f50b17f24f0aea088fa85a7711f8236636"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31dcdcba1c5f8d894c1024764955a6dbd58a258d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8bd6642b5092bf1fce15923254d0725c3ef8ee7dc4b73503ed6aaa66b67928de"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95d286a7904216f1fa4944d9b785c18780370419"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "440ef51827f64a8f464bf0b2e1d913c77bd4b893653d2b3070808a6319fbb021"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0cff62bd0facbba0c6457b474b302e0dc8d7d9b"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "485eb204cb5896725d80cca929968671d2eb5c015a574d0f6d7e015633055fa9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6d7226e0f6c3e22cd612d960061787b07bb2a36"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8afacb28d1fb7a6c462ec8a42e6ae08c043e999808fa5e843bff9426697ddb0c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deac6b59015b0bc74d169e6a882a89af1dc3ad68"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "4fc75c2c1425d4eb919eadd04a7bb3dc4a30a83e9c675bc6dc960582dd7121b1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "58898244d7b4dc2508ae46db3a8eb36bcf1aa13c"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "41c54c97ee48f93eecaae15c4f6860c93c129f5b622ab3c0fdb6228d542ef01d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77d9e472214b213f7383814b3551a5dd048d0142"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "5b7d179d8dd418b5d7de0b28ba570ff146b0931487e37b9e11de532557a83948"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53bbc5976a2bf08a04ff861d9e25e55166c36743"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "d247db4144a0cb00ec993eec4f317d6ae7d75ba6a53efca4b1a9ed254c8c6653"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3389dc9d75dcbcc473180e37284496ef3083561d"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "d1bd195b5ff49e17478a76a521585c530ded2738127e9072a4c457ebec755aa0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b041b77bdf6db56fd10137ca96654ea180584ee"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "379ecb6c0fd4f5d0d621813792f559425ac89827838b3d25c509c5f300f6c724"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "3420c6e0d77d9514dd4eeef8ea0279e8399fcf74"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "558f939c287ec7863b94b2ad8bbc78deab34e2b38c6584a28e268b5b0769ee04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.201+0/GAP_pkg_json.v200.0.201.x86_64-unknown-freebsd.tar.gz"
