[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "93aede1b660a4045185b793092fe79c1ef8e22d7"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "e4eeae0319c7ff3a518bcfe1914fe8955a5da3c898331c9693ff454c9197014e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49800bddde34ea8dcd1e58ef2720bed820e41e6d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "c6c47cb99e7c5513b5d30542eebaf846415763584e74792830c90e8c3df9d3aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02d1ac38ed9a8af98fb5ac4617e6c189b2bf680b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "d0b74cd841f75d2adf4abeb45d843cdc08698d36a1ad13e57cbe6ecf4e5c54e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c96d1f6ed481bb07d6fc3115fbf38d2f8daef182"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "9aae730f56751d9c0885297e5d6094d9f633e02ffebd5337f5ac3fb772deeb0e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80ed5458d4ad04ee19926d0a7f5d889a78736893"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "103b49d6fa38729d8c416f1e2906a6ae65d3422b7558cfa821aa7849eeb8042f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e6720b103a57c1a6f85fd917f4abac4f82e8999"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "dda4364b95cac7f57f663dbd8cc9d9602de27d355135523461e405d02887ce5f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e15c1981febcf61c69bbe268faf7d9d807b5e080"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8de82d715bdde16b480e1efe3cc2f59e402f6db320b414bcabdf96468eff3978"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "b1673695470820b007523599217e542196b7cbc6"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "1562415ddb912a26dcc494f4bc4a0967f28c01aa10f9bacddb449558ee4af6c7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d302ba57d3b6d7b1d7b9fb551a3a3e5eca0afc1b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8eec8a707ba196cd1eb5fd60df8f95d0f43e72e19d07917e84c411cee9830225"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ba7784bf5176a99fc04219e7e31226b547d0480"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "aefa73e5f606a7376742c8ba9d2ea0d05e60c63f1c44a164edb10a8cabb50be8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bad5c45c27cf93c7eb759b63098c252131853342"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "7a1a9ca591fe886cbe1ebb9da4e3d90224571beb8b1fd40e829a5c0d46a045dc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9897cb6a1eeae368a1a8f3300c7936076df4ac9"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "352e299b55b983ca6d3175bcdbac5f34080d108b36c5008b6206d1325649f4f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "c3a7b15be5eced412917d40b7b99099a4d88e551"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "c35ed3bac7c7aa2bc6125ea61e51a5bdaf2ef8fe6d4ea2fbf8f45602ed87023c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.0.200+1/GAP_pkg_json.v200.0.200.x86_64-unknown-freebsd.tar.gz"
