[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "88098f6125372a585879a81bb4a2ee9b25a4e9f9"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "6509c088297e5b15628c56bd9d5eabf9fe77d3440959d40ffe35143c645e0cc8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cf20f5bf2955e061ac9e97e85499096d00f5fb5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "00e6518c223da12655553bb0fc881896edd7bc5f262c55b45c6b052c5ddb13ce"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c1a4acd23d4c70fc2eb55efb0ccf76b54317583"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "0bcbf0d48165dc1415327ef00fdc3a3d75d256b7233a4509b89772e0e0c56d3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a102ef639445b9913330566c04d8171c9d7645fc"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "33bd528ad935f0fc3864f9428f5d5c362e29ba24a9cf6dac8aab1296c25aa68e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71b713a63b51cc5c5cceb216e9d9eb8177cbbc58"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "6aa3f1ae99feff5ce78889bbf3b4a66a2eaaec63db38507f67b35d60a1ef1c06"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c43dcd28ef3f80e21be2b95753c1e42d753fc3f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "40e05879c139a23b71677a00ccfcc8f917b10ac517d304d75ec7c026bc34db4e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f2ae3cee5fe39afff952446496f137a07619f0e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "51b8a097960d4a1f4a1c5bb214e1bac70652886ea611073311d0aa22ddce6587"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "7ccfaec2905df4944421c6969f4d4fabca7dddf3"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "996f67de4c576e3cd0e4b0331f969b81197cd902dce934c1739ce9365f2af008"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f7008b0657167b8ff332de78b9bbc730087344e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b2f37f8965dfc3835631329618fcb75b2732f712d716518e2bedb4e48e2befbe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6623091b383321115da21198fc0c0b967f81528"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "75acc04f4625667988155228a9fd6e88c3086e9ecb3f0535553edd338e74d940"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "815b11e1302ecd5c977e833ec85498cb08d87857"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "e1c4ecadc3d5a3ece08a6ec49f93bfc88767c1c98a8a6e195af1c24d54acae4f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5b55a2aaf6b377aeb4f60baaeeec6d8b9a39277"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b0e9e3bf3674743a2bf949dd16860322a051583818083cadc7d47e7ee793c461"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "34d1f408a5c5b6a8b27cbc0b3edde1724fc53b7d"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "669dd57333c627572394973f792109166f99211de9197e0612cd536472eb78ab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.0+0/GAP_pkg_json.v200.200.0.x86_64-unknown-freebsd.tar.gz"
