[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "23b5ed404eb180bbb63877c2d7fce81d789e7141"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "35fe5531b1b5b8cc520d69c6d090fb399d15169f9310bfcddd15d092a3639a76"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "918ccae3eaaf46d0b78c9bce2622ccf1d6dc3e0a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "451aba9c57fd79fa7cf5d5f5a87e04fb91a58a576164fd44d7e806f211b02f58"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b336e0ed9829ada8148baa8968e1e2d373eea4e1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "89389581e4382b6ebd5cbc474a2544c365517d859819fa8b58324939dd2bf03a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1ac2846d295c16fde15ccdec75c2abc725d63c8"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "7bccb28548d6cc101c1501a6141f5affed7b29a16c9ff9f7057ae4b50922f6eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2a693c30b56716e46c6e78a724b20d6f7a0ef06"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "439938af1f28b969ff2966a1e945dca01d7d04ee330293b033e92466ea1cf902"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "04db06b6eed1623736d2546d54c4be78f8e91354"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "faf17d33d81f3e62c9e0c143352753eed18b3eddf7f6be7bcd11711d6d315a74"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8767d3791c987f7328e58c29e92d2aa3c001c6dc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "25788cdbdb0bd84c60ea7319564b076a4e994e3152174a439b4850a749c3bee3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "753533e1df8694d610870c68561fec1900d9fb02"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "07ebba3ce32c7fedb3461f876de022e6b33e288b07ae8fc15e89f294ba5aa610"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d1b2c2230c3295942b79f4a2da832666e076656"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "15030df06db799752ef09473f694349a9318948c112034ed355c293b127def7d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.riscv64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "981b7ba31136bb608ac2fa8c7bd4b45ac56c5c84"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "3399881de97243f38d7e6fec85faf802f3a254d006f5ca3d5fed80d4e89df359"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "c9aec8d1476e0a9810818fdcacc6327ac9353754"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "65feeed9d843bfa46c2342b6dc8ceed3a89e15d0108ca08de3b73b14b6ba6a3d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "588a450524fb00fc17cf647170d7cc96f927b47d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "7f68bd901cf81f83b7a5dd198b1fd5e5a5634a4b1bd97a7943b77e4b7eb576ee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfb6b648a50657386adfd2b75756bfeb1246acbc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b46335eaebfc14528a5cf398bbf5c39862baefe0089be3901842f38137f6e503"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da8a209d4523376859cfdfb4df1cff267ae8fa88"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "823b715d6a36ad32e29aa25ca967d94720b63f7269c7f221ffd440a6b9da7045"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1637ab97c97f86e04d025dcd319ca9efbff5ad43"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "deac7cc3c7fb883b6c9eb1deccc42320c9bff552a13d858a22d1cadc549bc6b9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "bc2eeee1ad67b9d472d88cb80f33813f940a3088"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "d0383dbd6fd9239868bf89399ef5f1e6131bb34500ed3ca017ab12259bf3308f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.201+0/GAP_pkg_json.v200.200.201.x86_64-unknown-freebsd.tar.gz"
