[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "e52f28d91bb9ae039763337cbc2d1a5fc074a2f9"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "8f32482e456e18c653d6e0f61552aa77eedda1e5a99981cf9decd3562f9e57b8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a34d9b0c19dd6f666d8c42353e575829bde9eab"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "1d1206c930a9d1ff955311c89aa98bc12f65386ae3c4dd2c0ecb968e37dc6f45"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "872de013ac62a4307f061b8d25d8193d5d5f99e3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "4fbcf57f5a579e91b7c63ae3eae66bdbd9fa254a12831387ca5e2923c0546cfb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0d2acf9dca2e9e772bfb4ccca6b2a8558562297"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b9884e1b5429312118b8a40feab18eae5623879b79ee9e0f6ce086cf52c56931"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff95e9273634b1836eaf415888f4cf55f7b57ae"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "ba8f73f43e0982e672cc0cb4e08ec23242263855253f4a247ba4de1665620d8c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a355ab10aa1c38ea4a0e11b90531e2a424a6b925"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "f0637426e9b4a4c42dd61654efdae4587d8de46abcd0a0af5db0128309088d43"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c6afe5eb64337ce97eb319bacb9245ef594ea37"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "c880db49b687a92e49da866b1f3fbfb4a7be10fb0ee3dd220a0cb2ce63661dc3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "92a6615acc41447e99e18df2f01647b40464f7aa"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "8fedde8eb1c3283de5960d8f108465d764eeea0c5cd9cab73711be8aa1dd08d8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2abee80a8813e05999e0e0a93d4646cffa685e89"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "20c70d0108486f4bf07266682a0df8ea54ee3b718528a66bd1744b92e39a8e3f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77d7cf76be853678eadcb684eb3d3b4c58402d92"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "ef08a030fed235b353e4bdd3670a313a54b9757096b80d59349e748cea333d2c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a14ef80aa9373190641c55699e05746beef5deb"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8c7b11b51a108af1eea1bbc8bcaf42ebea4c586690cdca1044fa5fa4179bb65a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c2ad9543314931da352294a820c335fe5fcbe62"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "88bbe2e3df03ca6f76b74ea49d3e921d8a82728df9a949ecec9643db3767f3fa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "66ac53a639d2ce49787d7e364950dda359242205"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "1d20599cc519f8d24684f72b057bc65315e1e09917e0f5283362c5aff74b917d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+1/GAP_pkg_json.v200.100.100.x86_64-unknown-freebsd.tar.gz"
