[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "4ba6e6161c52822cdc5e45e2a9398d8a2f562a22"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "68a7fbbdd0002876e7c077b6f19ce01269750f266fa221771ef8ae9b2e32845f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a555a47d2f7e27e9f0476dfaa64abb2f9b9363e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "f2974fbfe421789aab13db642cdfe3dd440f746867b7d9462fa6614a65bd54f3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e30229e7ae081a1b354a8202b328ffc2067271b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b70274ff5b168029972f2186d1ba078ffff978fa80ff8c6d5d7b1d22e2cbea9c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9e77a67f2a89da6945dab93aa4124ef7cec96ff"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "3b7fdfe171c082f7aefa76f0e47f6e161d6733a196c6ef0a9bdde791edcb79ca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cbcfe71b41b5e5758093f63ca558cb7807147fe"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "6803efb1abc9e74f74027fc97f645a32de927d2ac05629403c96b3e63440c1e2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "673a888d67d849db372dd176bab0868789b2c9ec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "ea462d7f5efeef7402dc271ed1ea8db8a5aed013ace83581e9cb01d8d0b65970"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ae4c9004de4ebc3e94edfe8e6da3cae729e5919"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "e63dde70eeb4a2041f100ec9f9f40831a5bc12045192e9c901949946c4748422"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "9073e7cf1c225d1152a815b83618fbe4c25e5f03"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "3232b433deb76c26320bb48314a9b4d25b315dd878fbb074dabb5e032083d877"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cec0deb8274b4a08d645358db75552a29c7dc73"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "eb8b7f6460642e57b77936d61b495092319c013ac9d569cc206a63d823c36e85"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95dbe7e3f01112a452799d82a86a241d1c0924ae"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "2b12398ec4c48f729063ef5f11cb3e653a86b27be3555f65eaa519b78b1f5cdc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "104443fb6024ef77149da581ce484eb716a51e12"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "0697979821533912f3ce1dc30994db9b3b6675c9984beed43a11156843f42993"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3215b56ac3315044fa8e841c4fc40766085d1424"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "727d9a3a083737f8ee54ea82d27115daa362313899d2bda393c24983dd6340c9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "761bd34689eabd0ebd4a4652296c7f9dc61709a3"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "6a2f9a9212114044a5a31fd99ac033b0277337225be4779abfaeb10799f7281d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.200.200+0/GAP_pkg_json.v200.200.200.x86_64-unknown-freebsd.tar.gz"
