[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "72b7af49b67f573b3c8fa6801653b7dfc8d11c23"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "41fd30ef2a962c8ede96f0915abeafb3be93c8d70d6f0e45cb912ab40a913b67"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83cd89aec81d60fd55ed713beb340bad287387bd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "3beea8321d03a1a07986e4a2afa3aded629150213f6817c05272bc5a50b675ad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4ca039ea0f6d9b09f042c90a236516fbcd21b74"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "bd2637b0bec5c5c0478fb7636e5a34c7792e28f347ea129268e1db919da1941f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "799d6270738e6af9156ff3fa48f1e897435d91e8"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "1ac43f982fb62d65940b4253e8f33da3e5827b829fabebacdd39d01e0a296cff"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7789128389bfe98cd6a520f3213722211937c56e"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "32fdea1a16fbc944e4221e7ecafd3608435e7aa0e0457e5f9e27ec228e1b8474"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "589c1abf6ca59f767e7d74cad0fa208b13e3b396"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "dcb320616512c0a74e7816cc67f100728932f9d4f887615da8cfdee7ff534e73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "096d8f540b582523132ca3b4d6a2ccef0b829442"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8d2724cbd06999a072e978432f480315e736fd50eb8fa3bf9bae84d2e7e50c6d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "426e08a2bf2d8a57c48ea68a50054615a31eb7db"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "9cda2105b4f2b39cc44253a40360ebd3a67f6e28084991bc4f426c83b505e98d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f2d82465cb1284f94e84a7fd00a72e70c4c77fa"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "c643ca7fab0b663ee6e683570e883edaea1a8f6f91cee0c3a3511cdd0eb88fee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f459c4bacf5c7753358965100273285ad01d2e50"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "b076ed69df58a536a4d7d5684ace5c4e40374a8bf9fef7306346082056bf8fca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4be0326fa0655bf3713f2489bb70a56a9215abcd"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "607cab1506041d0b505474c0b716a63ee1dda87b49b4078d51409fa4e58b92cd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abe57096bc48350e89caadd10e4d0a4fca985484"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "21daa4959af0451a4b9e94e1e04add8a72b2f76f099f988da6e6445f24c5259b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "3c57c236510711e1a221859ac61dc9a32ed75b4f"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "a027888093c3c7219c06ac2c7d9c993395d68946253d9837bee04aacbc49bf4f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.100+0/GAP_pkg_json.v200.100.100.x86_64-unknown-freebsd.tar.gz"
