[[GAP_pkg_json]]
arch = "aarch64"
git-tree-sha1 = "4f5b07fecc830a73e117dacc0152de7a11c1f72a"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "2676dff7d8b59c0ad9ae9815e27f4600e898d34892fb99f5632109e70dd5bf97"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "505eebfbee1fe7edf6fe7240cbeaaef647b91e5f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "a478599d1dbcd95c024222de480f836eb6bcba94a05cb8e7aacaf0451bf9c6e3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b446b1ab205f23f760a8805876b5851a4d60ce8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "8f8157d9f347d9e20b609dbcb9d0b8904a821bba0bd44b0f8ff3e7454ef6cd63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82322714cad9070543349afbbf4f4ecb7b32aacd"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "4cc7027ce92597c40368dc17bc5f6462cd768927e8e90b44b0e234ad1f01e7a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18dfca31a970e54b7e645da390702f2db6900cf0"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "fa37d2f24cbfd036875413978c36ab19aa87200ff8f39e7423e28d6ef5061db3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85ba7fa2c72627163af9653810ebefd3977da41b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "304c881a09477846dbbbd0b2b6a6e23dbff11962518fac9b8c94abf133f2264c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70a0f4d4903ce546a13d8d54dc75b5b95eaf78d1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "47d00bb38d992f499428a2a1789e3c31ab5af2a9752cea9ae7058f50eccccdd6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "f7498261e318b7e20a9ecd457e4baa97df1ce170"
os = "macos"

    [[GAP_pkg_json.download]]
    sha256 = "7a24e53473ae01a8b11a380fbaa28f01ba7c806ea8d1eddce8fcc26a9016550e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eab84f1b7e515a8bcde59d8fcfd1b097980e268d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "95a89d2fbab17374cccc993477737ec53480097550f70d93ee30d2a3996d8b48"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89db789507a2a891922a6f77d16bc12fe9eed937"
libc = "glibc"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "71430e09bee1f6daf3d0a8ce7dc1bfbdd0e565784059d0e94f652565532044f6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40b42c8b7b0cc50f146c43c13e7dbeaeb5ba5e71"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "7115ec686fd88d5bba57486bcdd530ccb8f7a6b0ab8e7176af7dac0448302530"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f826143c373dec59c9aa98318f5a5f2a7ed3c81c"
libc = "musl"
os = "linux"

    [[GAP_pkg_json.download]]
    sha256 = "d20f82cffc4c1503d0cba586c33262549a71b301e96d5c7ded3794c387758859"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_json]]
arch = "x86_64"
git-tree-sha1 = "5af30fc6b3ed7b6c8553b787df2320bbea697fd9"
os = "freebsd"

    [[GAP_pkg_json.download]]
    sha256 = "43f482f8b20cb79e48d53ac191d3559070b6660f1905533e1b317c701bddd05a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_json_jll.jl/releases/download/GAP_pkg_json-v200.100.0+1/GAP_pkg_json.v200.100.0.x86_64-unknown-freebsd.tar.gz"
